languageCode = "en"
languageName = "English"
displayName = ":gb:"
isoCode = "en"
weight = 2
rtl = false

title = "Florian Linscheid"
# logo = "img/favicons/mstile-150x150.jpg"
description = "Personal Website by Florian Linscheid"
copyright = "&copy; 2022 Florian Linscheid"

dateFormat = "2 January 2006"

[author]
  name = "Florian Linscheid"
  image = "img/IMG_0827.jpeg"
  headline = "PhD Student, Programmer, Coffee lover!"
  bio = "This is an example author bio, and although there's a stock photo of a dog here, this article was actually created by a human. :dog:"
  links = [
    { twitter = "https://twitter.com/linschfl" },
    { linkedin = "https://www.linkedin.com/in/linscheid-florian/" },
    { youtube = "https://youtube.com/" },
    { xing = "https://www.xing.com/profile/FlorianFelix_Linscheid/cv" },
  ]
