languageCode = "en"
languageName = "English"
displayName = ":gb:"
isoCode = "en"
weight = 2
rtl = false

title = "Florian Linscheid"
# logo = "img/favicons/mstile-150x150.jpg"
description = "Personal Website by Florian Linscheid"
copyright = "&copy; 2022 Florian Linscheid"

dateFormat = "2 January 2006"

[author]
  name = "Florian Linscheid"
  image = "img/IMG_1226.jpeg"
  headline = "Researcher, Programmer, Coffee lover!"
  bio = ""
  links = [
    { envelope-solid = "mailto:mail@florianlinscheid.de" },
    { linkedin = "https://www.linkedin.com/in/linscheid-florian/" },
    { xing = "https://www.xing.com/profile/FlorianFelix_Linscheid/cv" },
    { researchgate = "https://www.researchgate.net/profile/Florian-Linscheid-2" },
    { orcid = "https://orcid.org/0000-0002-9324-1764" },
    # { twitter = "https://twitter.com/linschfl" },
    # { youtube = "https://youtube.com/" },
  ]
